Feat/lessons module
DanielHe4rt/basement-lms pull request #31
Opened 2021-08-27 23:06 UTC by DanielHe4rt

```
.
├── Contracts
│   └── LessonTypeContract.php
├── Database
│   └── migrations
│       ├── 2021_08_05_204003_create_lesson_types_table.php
│       └── 2021_08_05_204244_create_course_module_lessons_table.php
├── Domain.php
├── Enums
│   └── LessonTypes.php
├── Http
│   ├── Controllers
│   │   └── LessonsController.php
│   └── Requests
│       ├── CreateLessonRequest.php
│       ├── UpdateLessonRequest.php
│       └── UploadLessonVideoRequest.php
├── Jobs
│   └── AzureStreamingEncode.php
├── Models
│   ├── Lesson.php
│   └── Type.php
├── Providers
│   └── LessonsProvider.php
├── Repositories
│   ├── LessonRepository.php
│   └── Types
│       └── ArticleRepository.php
├── Resources
│   └── views
│       └── components
│           ├── lesson.blade.php
│           └── types
│               ├── article.blade.php
│               ├── quiz.blade.php
│               └── video.blade.php
└── View
    └── Components
        ├── Lesson.php
        └── Types
            ├── Article.php
            ├── Quiz.php
            └── Video.php
```

2021-08-27 23:15 UTC, caiodomingues requested changes
.

2021-08-27 23:20 UTC, arthurtavaresdev reviewed
Vamo fingir que entendi as gambiarras e deixar passar hahaha.

Mas adiciona pelo menos alguns
 // Todo: para refactor no futuro.

2021-08-27 23:20 UTC, arthurtavaresdev commented on LMS/Lessons/Http/Requests/CreateLessonRequest.php
> +            'course_id' => $e[$maxIndex - 4],
Porque -4 e -2 ?

2021-08-27 23:20 UTC, arthurtavaresdev commented on LMS/Lessons/Jobs/AzureStreamingEncode.php
> +            sleep(5);
Huuum isso me parece errado, mas ok

2021-08-27 23:20 UTC, arthurtavaresdev commented on LMS/Lessons/Repositories/LessonRepository.php
> +            throw new \Exception('aaaaaaaaaaaaaaa');
Textinho mais descritivo por favor.

2021-08-27 23:39 UTC, DanielHe4rt commented on LMS/Lessons/Jobs/AzureStreamingEncode.php
> +            sleep(5);
Sem o sleep, vou ficar metralhando a API dos caras de requisição.

Não acho que seja errado nesse quesito.

2021-08-27 23:41 UTC, DanielHe4rt commented on LMS/Lessons/Http/Requests/CreateLessonRequest.php
> +            'course_id' => $e[$maxIndex - 4],
No caso, queria tentar deixar o controller o mais limpo possível e passei a validação geral pra classe de validação.

Tentei fazer algo bem simples pra pegar da URL os ids e mergear na validação principal.

2021-08-28 00:57 UTC, arthurtavaresdev commented on LMS/Lessons/Http/Requests/CreateLessonRequest.php
> +            'course_id' => $e[$maxIndex - 4],
Ok, isto está correto.

Me incomoda ainda a utilização do explode para solucionar isso. Mas não vejo outra solução melhor no momento.

Talvez alterar essa id's serem passados como query params, talvez...

2021-08-28 00:57 UTC, arthurtavaresdev commented on LMS/Lessons/Jobs/AzureStreamingEncode.php
> +        if ($this->lesson->getStatus() != 'waiting') {
Considere colocar status em constantes

2021-08-28 00:59 UTC, arthurtavaresdev commented on LMS/Lessons/Jobs/AzureStreamingEncode.php
> +                'url' => 'https://basement-brso.streaming.media.azure.net/' . $path['paths'][0]
Colocar variavel no ENV/Config

2021-08-28 01:01 UTC, arthurtavaresdev requested changes

2021-08-28 01:01 UTC, arthurtavaresdev commented on LMS/Lessons/Models/Lesson.php
> +            ->height(232)
Seria possível recuperamos estes tamanhos de maneira dinâmica de alguma forma ?

2021-08-28 01:01 UTC, arthurtavaresdev commented on LMS/Modules/Http/Controllers/ViewController.php
> +        $this->middleware('auth');
Isto não deveria está no web.php ?

2021-08-28 01:01 UTC, arthurtavaresdev commented on LMS/Modules/Resources/views/modules.blade.php
> +                    toastr.success("eaeaeaeaeeaeaeaeaeae")
Ajustar mensagem de erros.

2021-08-29 17:53 UTC, DanielHe4rt commented on LMS/Lessons/Models/Lesson.php
> +            ->height(232)
Acho que não sei se faz tanto sentido. Poderia ir pra uma env da vida mas a ideia era só pra gerar algo visualizável base pro layout não ficar "pobre".

2021-08-29 18:03 UTC, DanielHe4rt commented on LMS/Lessons/Http/Requests/CreateLessonRequest.php
> +            'course_id' => $e[$maxIndex - 4],
Acho válido a gente dar uma estudada nisso mais pra frente e abrir algumas chores. Isso também tá me incomodando, mas não achei nenhum jeito mais inteligente de isolar esses dados.

Em si a ideia de colocar números estáticos já sabemos q pode dar merda num próximo momento, mas até agora não vejo isso acontecendo.

2021-08-29 18:19 UTC, merged