feat(system): sorry for this huge commit
DanielHe4rt/basement-lms pull request #32
Opened 2021-08-31 23:43 UTC by DanielHe4rt

2021-08-31 23:54 UTC, arthurtavaresdev commented on LMS/Courses/Database/migrations/2021_08_30_051351_create_course_users_table.php
> +            $table->foreignIdFor(User::class);
God! Nem sabia que existia esse recurso

2021-09-01 00:04 UTC, arthurtavaresdev requested changes

2021-09-01 00:04 UTC, arthurtavaresdev commented on LMS/Courses/Http/Controllers/CoursesController.php
>          return response()->json($deleted, $deleted
```suggestion
        return response()->noContent()
```

2021-09-01 00:04 UTC, arthurtavaresdev commented on LMS/Lessons/Repositories/LessonRepository.php
>          dispatch(new AzureStreamingEncode($model));
Namoral, usa um pattern pra fazer algo mais generico

2021-09-01 00:04 UTC, arthurtavaresdev commented on LMS/Lessons/Repositories/LessonRepository.php
> +            $model->update(['duration' => gmdate('H:i:s', $duration)]);
Gm date ? what

2021-09-01 00:04 UTC, arthurtavaresdev commented on tests/Feature/LMS/Course/Http/Controllers/CoursesControllerTest.php
>              'cover' => UploadedFile::fake()->image('fodase.png'),
ajuda nois.

2021-09-01 00:04 UTC, arthurtavaresdev commented on tests/Feature/LMS/Lesson/Http/Controllers/LessonsControllerTest.php
>              'video' => UploadedFile::fake()->create('fodase.mp4')
ajuda nois.

2021-09-01 00:23 UTC, NicolasPereira commented on tests/Feature/LMS/Course/Http/Controllers/CoursesControllerTest.php
>              'cover' => UploadedFile::fake()->image('fodase.png'),
Viva o opensource HAHAHAH

2021-09-01 00:24 UTC, NicolasPereira commented on LMS/Courses/Models/Course.php
> +    public function getLessonsCountAttribute(): int
Apenas uma dúvida de aprendizado, isso não seria melhor retornar dentro de um service? 
Tipo o service acessar a entidade pra retornar quantas lições tem ? 
O mais correto n seria tirar essa responsabilidade da model ?

2021-09-01 00:28 UTC, DanielHe4rt commented on LMS/Lessons/Repositories/LessonRepository.php
>          dispatch(new AzureStreamingEncode($model));
Gostaria muito de fazer isso por agora, mas não vou conseguir.

2021-09-01 00:33 UTC, arthurtavaresdev commented on LMS/Courses/Models/Course.php
> +    public function getLessonsCountAttribute(): int
No caso como trata-se de um mutator/acessor, não faz sentido. O Service é para fazer o meio de campo entre o Controller e o Model. No caso estamos alterando algo que já vai está dentro do Modelo em si.

2021-09-01 00:39 UTC, merged