Feature/user profile page
DanielHe4rt/basement-lms pull request #37
Opened 2021-09-13 04:53 UTC by NicolasPereira

├── Http
│   ├── Controllers
│   │   ├──MeController.php
│   │   └── ViewController.php
│   └── Requests
│   │   ├──UpdateMeRequest.php
├── Models
│   ├── User.php
│   ├── Address.php
├── Observers
│   └── UserObserver.php
├── Providers
│   └── UserProvider.php
├── Repositories
│   ├── MeRepository.php
├── Resources
│   └── views
│   ├─── profile.blade.php
├── Domain.php

Fiz a criação do User Profile, no momento trouxe apenas as informações! 
Após a aprovação deste PR vou trabalhar na tela de alteração dessas informações (UPDATE). 

Observações:
1 -  O campo `last_seen` está como string e por isso não consegui usar o format do PHP para resolver a formatação! @DanielHe4rt, tem alguma de como posso resolver isso ? 

2 - Não consegui assinar um plano pro meu usuário aqui, fiz então
```
<p>Plano Atual: {{ $user->plan->name ?? "Sem Plano"}}</p>
```
acredito que esteja funcionando, se puderem testar na maquina de vocês e ver o fluxo seria top! 

Valeu galera :)

2021-09-13 12:03 UTC, arthurtavaresdev requested changes

2021-09-13 12:03 UTC, arthurtavaresdev commented on docker-compose.yml
> -# For more information: https://laravel.com/docs/sail
Pq removeu o Dockerfile ?

2021-09-13 12:03 UTC, arthurtavaresdev commented on LMS/User/Resources/views/profile.blade.php
> +                        <img src="https://placehold.it/300x300" class="photo-profile">
Não deveria estar puxando dinamicamente ?

2021-09-13 12:03 UTC, arthurtavaresdev commented on LMS/User/Resources/views/profile.blade.php
> +                        <p>Plano Atual: {{ $user->plan->name ?? "Sem Plano"}}</p>
```suggestion
                        <p>Plano Atual: {{ $user->plan?->name ?? "Sem Plano"}}</p>
```
Caso ele não tenha plano, a exceção já foi colocada na tela ao tentar acessar a propriedade name

2021-09-13 12:03 UTC, arthurtavaresdev commented on LMS/User/Resources/views/profile.blade.php
> +                        <p>Endereço: {{$user->address->street}} - {{$user->address->number}} - {{$user->address->neighborhood}} {{$user->address->complement}}</p>
Isso poderia ser uma mutator `fullAddress()`,
 imagino que esse padrão se repetirá.

2021-09-13 12:04 UTC, NicolasPereira commented on docker-compose.yml
> -# For more information: https://laravel.com/docs/sail
Pq era do meu ambiente local, com minhas váriaveis e afins! Como rodei no sail ele fez algumas alterações, será que ele tirou todas as alterações do dockerfile de fato ?

2021-09-13 12:05 UTC, NicolasPereira commented on LMS/User/Resources/views/profile.blade.php
> +                        <img src="https://placehold.it/300x300" class="photo-profile">
Ainda não tem a foto de perfil do usuario! 
Peguei o padrão apenas pra já ter baseado

2021-09-13 12:06 UTC, NicolasPereira commented on LMS/User/Resources/views/profile.blade.php
> +                        <p>Plano Atual: {{ $user->plan->name ?? "Sem Plano"}}</p>
Eu tinha feito isso e não sei pq apaguei! Vou aceitar sua sugestão!

Essa sua sugestão já é do PHP 8 né ?

2021-09-13 12:06 UTC, NicolasPereira commented on LMS/User/Resources/views/profile.blade.php
> +                        <p>Endereço: {{$user->address->street}} - {{$user->address->number}} - {{$user->address->neighborhood}} {{$user->address->complement}}</p>
Esse mutator eu poderia criar um método dentro do User, que retorna uma string já formatada?

2021-09-13 12:17 UTC, arthurtavaresdev commented on LMS/User/Resources/views/profile.blade.php
> +                        <p>Plano Atual: {{ $user->plan->name ?? "Sem Plano"}}</p>
Sim

2021-09-13 12:18 UTC, arthurtavaresdev commented on LMS/User/Resources/views/profile.blade.php
> +                        <p>Endereço: {{$user->address->street}} - {{$user->address->number}} - {{$user->address->neighborhood}} {{$user->address->complement}}</p>
Essa é justamente a ideia criar uma função dentro de Address na verdade, chamada (getFullAddress())

2021-09-13 12:29 UTC, NicolasPereira commented on LMS/User/Resources/views/profile.blade.php
> +                        <p>Endereço: {{$user->address->street}} - {{$user->address->number}} - {{$user->address->neighborhood}} {{$user->address->complement}}</p>
Beleza, vou implementar!

2021-09-13 12:58 UTC, arthurtavaresdev commented on docker-compose.yml
> -# For more information: https://laravel.com/docs/sail
Acho que não é necessário retirar o sail, apenas o re-instale através do comando `artisan sail:install`

2021-09-13 13:01 UTC, arthurtavaresdev commented on LMS/User/Resources/views/profile.blade.php
> +                        <img src="https://placehold.it/300x300" class="photo-profile">
Justo, caso não queira fazer uma implementação disso, peço que abra uma issue para tal.

2021-09-13 22:32 UTC, NicolasPereira commented on LMS/User/Resources/views/profile.blade.php
> +                        <img src="https://placehold.it/300x300" class="photo-profile">
Após esse PR vou fazer a parte do update dessas informações e já implemento nessa feature essa funcionalidade, blz ?

2021-09-13 22:33 UTC, NicolasPereira commented on LMS/User/Resources/views/profile.blade.php
> +                        <p>Endereço: {{$user->address->street}} - {{$user->address->number}} - {{$user->address->neighborhood}} {{$user->address->complement}}</p>
@arthurtavaresdev , uma dúvida! Pensei em criar
`getFullAddress` para retornar : Rua + Numero + Bairro 
`getCityAndState`para retornar : Cidade/Estado

Seria valido ?

2021-09-15 06:07 UTC, NicolasPereira commented on LMS/User/Resources/views/profile.blade.php
> +                        <p>Endereço: {{$user->address->street}} - {{$user->address->number}} - {{$user->address->neighborhood}} {{$user->address->complement}}</p>
@arthurtavaresdev fiz as alterações :)

2021-09-15 06:08 UTC, arthurtavaresdev approved these changes
LGTM

2021-09-15 23:42 UTC, DanielHe4rt requested changes
O código ficou bem organizado, só  dar atenção nesses pontos de limpeza e tá tudo certo!

PS: voltar o package-lock.json pro lugar para mergearmos.

2021-09-15 23:42 UTC, DanielHe4rt commented on LMS/User/Http/Controllers/ViewController.php
> +    public function viewProfile () : View
```suggestion
    public function viewProfile (): View
```

2021-09-15 23:42 UTC, DanielHe4rt commented on LMS/User/Models/Address.php
> +        $fullAddress = $this->street.'-'.$this->number.'-'.$this->neighborhood;
Pô, seria interessante colocar virgulas para separar essas partes do endereço, e deixar o - pra uma outra ocasião.

```suggestion
        $fullAddress = $this->street . ', ' . $this->number . ', ' . $this->neighborhood;
```

2021-09-15 23:42 UTC, DanielHe4rt commented on LMS/User/Models/Address.php
> +            $fullAddress = $this->street.' - '.$this->number.' - '.$this->neighborhood.' - '.$this->complement;
Repetir padrão acima.

2021-09-15 23:42 UTC, DanielHe4rt commented on LMS/User/Models/Address.php
> +        return $this->city.'/'.$this->state;
Colocar espaçamento entre os items e as concatenações.

2021-09-16 01:19 UTC, NicolasPereira commented on LMS/User/Http/Controllers/ViewController.php
> +    public function viewProfile () : View
Arrumei isso neste [commit](https://github.com/DanielHe4rt/basement-lms/commit/e6d319440de8defd0bf96ebbda06e90f17f0b328)

2021-09-16 01:31 UTC, DanielHe4rt approved these changes

2021-09-16 01:32 UTC, merged